### ISSUE TITLE
Submit to Upstream

### ISSUE THREAD

**Issue by tim-pugh** [clang-randstruct/llvm-project#13]
Send an RFC (request for comment) email to the CFE-DEV mailing list describing your work and soliciting feedback. 

We can put the code changes up on the code review website following the process described here 
https://llvm.org/docs/Phabricator.html 
under “Requesting a review via the web interface”. 

We can provide a link to the review in the RFC thread.

**Comment by tim-pugh** [comment]
After the RFC and fixing suggestions the upstream patch can be submitted.

We will need to do this ASAP.

**Comment by tim-pugh** [comment]
We'll likely miss the Upstream goal, but the RFC should be scheduled to take place Friday if all goes well. Running all the new squashed commit hashes appear to pass. Thanks @jcantrell  for the script to automate this and @connorkuehl for the git fu

**Comment by connorkuehl** [comment]
https://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20190304/263999.html

**Comment by tim-pugh** [comment]
https://lists.llvm.org/pipermail/cfe-dev/2019-March/061607.html

**Comment by tim-pugh** [comment]
Leaving task open for the time being so the code review link is easily accessible

**Comment by tim-pugh** [comment]
Links added to wiki.

Closing this issue on down!
