### ISSUE TITLE
Circle back to hash 57b2e55

### ISSUE THREAD

**Issue by tim-pugh** [clang-randstruct/llvm-project#41]
Need to investigate this error more:

/home/timpugh_pdx_edu/llvm-project/clang/include/clang/Basic/Attr.td:3215:24: error: Variable not defined: 'ClangRandstructDocs'
let Documentation = [ClangRandstructDocs];

**Comment by connorkuehl** [comment]
Solution proposal outlined in this comment: https://github.com/clang-randstruct/llvm-project/commit/57b2e55b8dade4a8ed6c4d6d94419fdd6aebd333#r32602114

**Comment by tim-pugh** [comment]
This issue should be squashed now. Thanks @connorkuehl
