### ISSUE TITLE
Add support for __no_randomize_layout

### ISSUE THREAD

**Issue by connorkuehl** [clang-randstruct/llvm-project#6]
**Is your feature request related to a problem? Please describe.**
One of our stretch goals requires this feature to allow application programmers to opt out of automatic structure selection.

**Describe the solution you'd like**
When Clang hands control to our plugin for a structure layout, we will immediately check to see if the structure has a `__no_randomize_layout` attribute attached to it. If so, we will not randomize this structure's layout. We will `return false;` and have Clang lay it out for us normally.

**Comment by connorkuehl** [comment]
Acceptance criteria:

- [ ] Add `__no_randomize_layout` attribute to the Clang compiler

- [ ] In the attribute handler, if the structure ALSO HAS `randomize_layout`, emit a compiler warning.

- [ ] In the entry point for our randstruct code, if the structure has `__no_randomize_layout`, do not hand it to randstruct!

**Comment by Nixoncole** [comment]
Might be useful: https://chromium.googlesource.com/chromium/src/+/HEAD/docs/writing_clang_plugins.md#emitting-errors

Connor sent this: https://clang.llvm.org/docs/InternalsManual.html#the-diagnostics-subsystem

**Comment by connorkuehl** [comment]
I suspect we will also want to include this in the regression test suite.

See #20 for an example of this.

**Comment by Nixoncole** [comment]
Looks like Jeff and I finished this, just waiting for code push on his end.

**Comment by connorkuehl** [comment]
This code got reverted at some point; we need it back.

**Comment by connorkuehl** [comment]
Closed in #39
